driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1
  - name: debian-7.8
    run_list: apt::default
  - name: debian-8.1
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

suites:
- name: default
  run_list:
    - recipe[ossec]
- name: client
  run_list:
    - recipe[ossec::client]
- name: server
  run_list:
    - recipe[ossec::server]
  data_bags_path: 'test/integration/default/data_bags'
- name: agent_auth
  run_list:
    - recipe[ossec::agent_auth]
  attributes:
    ossec:
      agent_server_ip: 10.0.2.2
- name: authd
  run_list:
    - recipe[ossec::authd]
  driver_config:
    network:
    - ['forwarded_port', { guest: 1514, host: 1514, protocol: 'udp' }]
    - ['forwarded_port', { guest: 1515, host: 1515, protocol: 'tcp' }]
  includes:
    - centos-7.1
    - debian-8.1
